line:
  api:
    redirect_uri: "https://line-login-starter-kabin-svvy.herokuapp.com/auth"
    token_uri: "https://api.line.me/oauth2/v2.1/token"
    token_code: "drUPcXpWS7fUDpSrZf6h"
    access_token: "eyJhbGciOiJIUzI1NiJ9.gYp-4ieS6GdXCU3QOduonlmLAU7E1Tz-DdksGX0a6SinuXLOSqos2Q6zBJiSze7leabHwQQT6DE4qGWtX4dHyzr5CfZZ_HYvU9d7bYRAAIVlCZttEcR4B5q_2SN1KOjD7Ly_I5j6btG0VoXwcNqtZqfxXNUeL9kc4SVVx9g6tFI.CKFYwLEzx63vtmFcWJGIZa1nLllmlpZquIUfhZI7h4E"